server:
  port: 8080

spring:
  application:
    name: ewm-service
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EWM_DB_HOST:localhost}:${EWM_DB_PORT:5432}/${EWM_DB_NAME:ewm-main}
    username: ${EWM_DB_USER:ewm}
    password: ${EWM_DB_PASSWORD:ewm}

stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
