server:
  port: 9090

spring:
  application:
    name: stats-server
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${STATS_DB_HOST:localhost}:${STATS_DB_PORT:5432}/${STATS_DB_NAME:ewm-stats}
    username: ${STATS_DB_USER:stats}
    password: ${STATS_DB_PASSWORD:stats}

management:
  endpoints:
    web:
      exposure:
        include: health,info